### ISSUE TITLE
Georgia

### ISSUE THREAD

**Issue by JesseWS** [sverhees/master_villages#2]
Hi!

One minor correction: In Chantlisqure in Eastern Georgia, Bezhta is spoken, and not Hunzib.
Also, I could suggest adding Kistian Chechen to the Pankisi valley. They are the villages of Duisi, Dzibakhevi, Jokolo, Shua Khalatsani, Birkiani, and Omalo (not to be confused with the Omalo in Tusheti).

Thanks!
Jesse Wichers Schreur

**Comment by agricolamz** [comment]
Hi, @JesseWS!

Thank you for sharing this information!

George Moroz

**Comment by sverhees** [comment]
Thanks so much for these data! I added the Chechen villages in Pankisi (altitude is not yet available), and corrected both the name and the language for Chantlisqure.
