### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by agricolamz** [sverhees/master_villages#6]
I think it would be better, if we have a different versions of this dataset in order to reference to. Imagine that I've done some work with one version, then something get changed and I can't reproduce my work since then. The versions could be implemented via [github releases](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository). It is also make it possible to get a DOI via [zenodo](https://zenodo.org/).

**Comment by sverhees** [comment]
Good idea, thanks!
