### ISSUE TITLE
cyrillic names in village names

### ISSUE THREAD

**Issue by agricolamz** [sverhees/master_villages#7]
![image](https://user-images.githubusercontent.com/15956515/86573676-67b5b400-bf7d-11ea-9351-d88793ad8892.png)

in [this](https://raw.githubusercontent.com/sverhees/master_villages/master/data/villages.csv) dataset.

**Comment by sverhees** [comment]
Please be a little more elaborate when addressing a problem!
These villages were listed in Saidova's (2007) grammar of Zaqatala, and we have no corresponding Latin names for them yet (nor coordinates).
Nonetheless, the next version of the dataset will have separate columns for Latin / Cyrillic village names.
