### ISSUE TITLE
Altitudes

### ISSUE THREAD

**Issue by MishaDaniel** [sverhees/master_villages#8]
Исправить высотность села Аща.
Какой у нас мастер-файл высотностей и диалектной/языковой принадлежности - туда же и кутанность указывать, и население? надо где-то онлайн все хранить

**Comment by agricolamz** [comment]
Да, можно здесь же открывать новое issue.

**Comment by sverhees** [comment]
Языковая принадлежность всегда была. Диалектная, как вы знаете, в процессе. Когда готова - добавим.
Кутаны тоже есть. В общем всё, что есть, описано в readme на главной странице репозитрия.
Пока я закрою этот ишю, потому что Гарик только что обновил высотность. Если высота с. Аща все еще неправильная, откройте новый ишю и, пожалуйста, пишите его на английском!
